Divide the workflow into two jobs Utilize GitHub Cache action.

diff --git a/.github/workflows/lua-lint.yml b/.github/workflows/lua-lint.yml
--- a/.github/workflows/lua-lint.yml
+++ b/.github/workflows/lua-lint.yml
@@ -19,6 +19,8 @@ env:
   FILES_TO_CHECK: >-
     script
   VENDOR_PATH: .vscode/autocomplete
+  LUA_VERSION: "5.1"
+  LUAROCKS_VERSION: "3.7.0"
   LUACHECK_CONFIG: .luacheckrc
   CUSTOM_LUA_GLOBALS: >-
     ardm
@@ -34,13 +36,110 @@ jobs:
         persist-credentials: false
         fetch-depth: 0
 
+    - name: Cache lua environment
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-lua
+      with:
+        path: ~/{.install,.lua}
+        key: ${{ runner.os }}-lua-${{ env.LUA_VERSION }}
+        restore-keys: |
+          ${{ runner.os }}-lua-
+
+    - name: Cache luarocks installation
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-luarocks
+      with:
+        path: ~/.luarocks
+        key: ${{ runner.os }}-luarocks-${{ env.LUAROCKS_VERSION }}
+        restore-keys: |
+          ${{ runner.os }}-luarocks-
+
     - uses: leafo/gh-actions-lua@v8.0.0
       with:
-        luaVersion: "5.1"
+        luaVersion: ${{ env.LUA_VERSION }}
         
     - uses: leafo/gh-actions-luarocks@v4.1.0
       with:
-        luarocksVersion: "3.7.0"
+        luarocksVersion: ${{ env.LUAROCKS_VERSION }}
+        
+    - name: Install luacheck
+      run: luarocks install luacheck
+
+    - name: Reset autocomplete
+      run: rm -rfv ${{ env.VENDOR_PATH }}
+
+    - name: Checkout PJ-autocomplete
+      uses: actions/checkout@v2
+      with:
+        repository: Warhammer-Mods/PJ-autocomplete
+        path: ${{ env.VENDOR_PATH }}
+
+    - name: Remove PJ-autocomplete meta files
+      run: rm -rf ${{ env.VENDOR_PATH }}/{.git,.github}
+
+    - name: Set Lua globals from vendor path
+      id: lua-globals
+      run: |
+        chmod +x .vscode/update_lua_globals.sh
+        .vscode/update_lua_globals.sh
+
+    - name: Luacheck Lint
+      id: luacheck
+      shell: bash --noprofile --norc {0}
+      run: |
+        mkdir output
+        echo "::add-matcher::.github/luacheck-plain.json"
+        luacheck ${{ env.FILES_TO_CHECK }} \
+          --formatter plain \
+          --codes --ranges
+        exitcode=${PIPESTATUS[0]}
+        echo "::remove-matcher owner=luacheck-plain_error::"
+        echo "::remove-matcher owner=luacheck-plain_warning::"
+        if [ "$exitcode" -gt 1 ]; then
+          exit $exitcode;
+        else
+          exit 0;
+        fi
+
+  push:
+    runs-on: ubuntu-latest
+    needs: lint
+
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        persist-credentials: false
+        fetch-depth: 0
+
+    - name: Cache lua environment
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-lua
+      with:
+        path: ~/{.install,.lua}
+        key: ${{ runner.os }}-lua-${{ env.LUA_VERSION }}
+        restore-keys: |
+          ${{ runner.os }}-lua-
+
+    - name: Cache luarocks installation
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-luarocks
+      with:
+        path: ~/.luarocks
+        key: ${{ runner.os }}-luarocks-${{ env.LUAROCKS_VERSION }}
+        restore-keys: |
+          ${{ runner.os }}-luarocks-
+
+    - uses: leafo/gh-actions-lua@v8.0.0
+      with:
+        luaVersion: ${{ env.LUA_VERSION }}
+        
+    - uses: leafo/gh-actions-luarocks@v4.1.0
+      with:
+        luarocksVersion: ${{ env.LUAROCKS_VERSION }}
         
     - name: Install luacheck
       run: luarocks install luacheck
@@ -65,24 +164,6 @@ jobs:
         changes=$(git status --porcelain ${VENDOR_PATH} ${LUACHECK_CONFIG} | tr '\n' '\t')
         echo "::set-output name=changes::$changes"
 
-    - name: Luacheck Lint
-      id: luacheck
-      shell: bash --noprofile --norc {0}
-      run: |
-        mkdir output
-        echo "::add-matcher::.github/luacheck-plain.json"
-        luacheck ${{ env.FILES_TO_CHECK }} \
-          --formatter plain \
-          --codes --ranges
-        exitcode=${PIPESTATUS[0]}
-        echo "::remove-matcher owner=luacheck-plain_error::"
-        echo "::remove-matcher owner=luacheck-plain_warning::"
-        if [ "$exitcode" -gt 1 ]; then
-          exit $exitcode;
-        else
-          exit 0;
-        fi
-
     - name: Commit files
       id: commit
       if: steps.lua-globals.outputs.changes
@@ -91,11 +172,15 @@ jobs:
         git config --local user.name "github-actions[bot]"
         git add ${VENDOR_PATH} ${LUACHECK_CONFIG}
         git commit -m "Update luacheck config"
+        if ${{ startsWith(github.ref, 'refs/tags/') }}; then
+          git tag -fa ${{ github.ref }}
+        fi
         echo "::set-output name=finished::true"
 
     - name: Push changes
-      uses: ad-m/github-push-action@master
-      if: steps.commit.outputs.finished && ! startsWith(github.ref, 'refs/tags/')
+      uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1
+      if: steps.commit.outputs.finished
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}
+        tags: true
